name: CI

on:
    push:
        branches:
            - master
            - dev
    pull_request:

env:
    node_version: 16

jobs:
    Test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  cache: yarn
                  node-version: ${{ env.node_version }}
            - run: yarn --frozen-lockfile --network-timeout 1000000
            - run: yarn test --ci --coverage --maxWorkers=2
    Lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  cache: yarn
                  node-version: ${{ env.node_version }}
            - run: yarn --frozen-lockfile
            - run: yarn lint
