name: CI

on:
    push:
        branches:
            - master
            - dev
    pull_request:

jobs:
    Test:
        runs-on: ${{ matrix.os }}
        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN_READONLY }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  cache: yarn
                  node-version: ${{ matrix.node-version }}
            - run: echo '//registry.npmjs.org/:_authToken= ${{ secrets.NPM_TOKEN_READONLY }}' >> .npmrc
            - run: yarn --frozen-lockfile --network-timeout 1000000
            - run: yarn test --ci --coverage --maxWorkers=2
    Lint:
        runs-on: ubuntu-latest
        env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN_READONLY }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  cache: yarn
                  node-version: ${{ matrix.node-version }}
            - run: echo '//registry.npmjs.org/:_authToken= ${{ secrets.NPM_TOKEN_READONLY }}' >> .npmrc
            - run: yarn --frozen-lockfile
            - run: yarn lint
